version: "3.7"
services:
  client:
    build: ./client
    ports:
      - "8082:3000"
    volumes:
      - "./:/app"
      - "/app/node_modules"
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
  server:
    build: ./server
    environment:
      - PORT=5000
      - JWT_PW=gaivota-test
      - MONGO_URL=mongodb://mongo/DemocracyOS-dev
    ports:
      - "8081:5000"
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ~/data:/data/db
